FORMAT: 1A
HOST: http://123.206.79.106/

# College Campus Oriented Social Media Resolution

This is for our Software Engineering class.<br><br>
All by<br>
SymPy @SymphonyPy<br>
Peter Santos @PTSTS<br>
bing yan song @Sporot

## Sign Up [/signup]

### Sign Up [POST]
+ Request (application/json)

        {
            "id":"david180313",
            "password":"123456",
            "email":"123456@123.com",
			"name":"David",
            "captcha":"F341"
        }

+ Response 200 (application/json)

        # 200 successed
        # 101 id is taken
        # 102 password and confirmed password are not the same
        # 103 verified code was wrong
        
        {
            "status":[200,101,102,103]
        }
        
## Sign In [/signin]
### Sign In [POST]

+ Request (application/json)

        {
            "id":"david180313",
            "password":"123456",
            "captcha":"IH42"
        }

+ Response 200 (application/json)

        # 200 successed
        # 101 id or password was wrong
        # 102 verified code was wrong

        {
            "status":[200,101,102]
        }

## Messages [/messages]
### Request Messages [GET]

+ Response 200 (application/json)

        {
            "timestamp":1520926923,
            "id":"david180313",
            "nickname":"David",
            "message":"Wow, the one who wrote this must be a genius!"
        }
### Send Messages [POST]

+ Request (application/json)

        {
            "timestamp":1520926923,
            "message":"Wow, the one who wrote this must be a genius!"
        }

+ Response 200 (application/json)

        # 200 successed
        # 101 failed

        {
            "status":[200,101]
        }

## Check Friends [/myfriends]
### Get Friends list [GET]

+ Response 200 (application/json)

        [
            {
                "id":"emily1328",
                "nickname":"Emily",
                "laststatus":"WHat a nice day!"
            },
            {
                "id":"john234",
                "nickname":"John",
                "laststatus":"I love programming!"
            },
            {
                "id":"dave874",
                "nickname":"Dave",
                "laststatus":"I've got a great idea! Need only one to code!"
            }
        ]
        
## Add Friends [/addfriend]
### Send request [POST]

+ Request (application/json)

        {
            "id":"david180313",
            "message":"Hi David! Nice to meet you!"
        }

+ Response 200 (application/json)

        # 200 successed
        # 101 failed

        {
            "status":[200,101]
        }

## Search [/search]
### Send request [POST]

+ Request(application/json)

        {
            "content":"Software Engineering"
        }

+ Response 200 (application/json)

        {
            "Courses":[
                {
                    "id":123,
                    "name":"Software Engineering",
                    "teacher":"Lihua Fu",
                    "location":"204"
                },
                {
                    "id":124,
                    "name":"Software Engineering",
                    "teacher":"Yifei Wu",
                    "location":"603"
                }
            ],
            "Teachers":[
                {
                    "id":234123,
                    "name":"Soft",
                }
            ]
        }